import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Rizfan Radya - Web Portfolio",
  description: "Generated by Rizfan Radya",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="tracking-wide bg-black text-white">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
